<?php
// TODO: check max size of this ID. This is currently a guess. (is it even needed?)
define('JOINDIN_ID_LENGTH', 12);

// TODO: this isn't always required but is here to ease initial testing
require_once('./' . drupal_get_path('module', 'joindin') . '/includes/joindin.api.inc');

/**
 * Implements hook_block_info
 * Defines blocks to hold the joind.in
 */
function joindin_block_info() {
  /*
   * TODO: implement blocks for the widgets
   * These may need to be views that take arguments? Look into multiple block
   * modules - is boxes still used on D7? Are there better alternatives?
   */
  $blocks = array();

  return $blocks;
}
