<?php
// TODO: this isn't always required but is here to ease initial testing
require_once('./' . drupal_get_path('module', 'joindin') . '/includes/joindin.api.inc');

/**
 * Implements hook_block_info().
 * Defines blocks to hold the joind.in
 */
function joindin_block_info() {
  /*
   * TODO: implement blocks for the widgets
   * These may need to be views that take arguments? Look into multiple block
   * modules - is boxes still used on D7? Are there better alternatives?
   *
   * Also need to consider how the code distribution will work for the widgets
   *  is it more appropriate to copy the code to this module? does the licence
   *  allow for that? Or should it be a separately downloaded library?
   */
  $blocks = array();

  return $blocks;
}
